# Generated by Django 4.2.2 on 2024-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogpost_content_alter_blogpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='blog_images/', verbose_name='Изображение'),
        ),
    ]
