# Generated by Django 4.2.2 on 2024-06-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='271396', max_length=6, verbose_name='Код верификации'),
        ),
    ]
