# Generated by Django 4.2.2 on 2024-08-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_block_users', 'Can activate or deactivate user')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='076123', max_length=6, verbose_name='Код верификации'),
        ),
    ]
