# Generated by Django 4.2.2 on 2024-08-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='926107', max_length=6, verbose_name='Код верификации'),
        ),
    ]
