# Generated by Django 4.2.2 on 2024-08-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0002_attempt_mailing_attempt_user_client_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client',
        ),
    ]
