# Generated by Django 4.2.2 on 2024-08-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0004_alter_attempt_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='next_date',
        ),
    ]
