# Generated by Django 4.2.2 on 2024-08-21 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing_app', '0007_remove_mailing_user_mailing_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='owner',
        ),
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
